### ISSUE TITLE
["FE/BUG"] Fix bug on explore page

### ISSUE THREAD

**Issue by nabutabu** [cse110-fa21-group1/-cse110-fa21-group1#141]
In the issue description, please describe the bug.
**Expected behavior**
Expect to show multiple rows of recipe cards
**Actual behavior**
Showing oversized cards instead, only 2 are visible
**Steps to reproduce**
Add multiple recipes to the local storage

**Comment by CrisostomoC3911** [comment]
I believe when this occurs, you need to apply the css styling from explore.css in order when creating the card.

**Comment by nabutabu** [comment]
Closed
