### ISSUE TITLE
["FE/BUG"] Hamburger Menu Maximized on Load

### ISSUE THREAD

**Issue by luosxaira** [cse110-fa21-group1/-cse110-fa21-group1#76]
In the issue description, please describe the bug.
**Expected behavior** When loading a page, the hamburger menu should be minimized.
**Actual behavior** The hamburger menu appears on load for any page.
**Steps to reproduce** Navigate to Explore.html, ManageRecipe.html, or Home.html.

**Comment by zimo27** [comment]
Fixed in Merge #71
